function AI_VisualLearning()
% AI可视化学习平台  v3.3
% 通过图形化可交互的界面，帮助学生直观理解AI算法原理。
% 按典型任务类型组织：分类 -> 回归 -> 聚类

    fig = figure('Name','AI可视化学习平台','NumberTitle','off',...
        'Position',[100,80,980,720],'MenuBar','none','ToolBar','none',...
        'Resize','off','Color',[0.10,0.10,0.16]);

    % ===== 标题区 =====
    uicontrol('Style','text','String','AI 可视化学习平台',...
        'FontSize',28,'FontWeight','bold',...
        'ForegroundColor',[0,0,0],'Units','normalized',...
        'Position',[0.05,0.88,0.9,0.07],'HorizontalAlignment','center');

    uicontrol('Style','text',...
        'String','通过拖拽数据点、调整参数、观察实时变化，理解分类 / 回归 / 聚类算法核心原理',...
        'FontSize',13,'ForegroundColor',[0,0,0],...
        'Units','normalized','Position',[0.05,0.83,0.9,0.03],...
        'HorizontalAlignment','center');

    uicontrol('Style','text','String','','Units','normalized',...
        'Position',[0.08,0.81,0.84,0.003],...
        'BackgroundColor',[0.3,0.55,0.9]);

    % ===== 模块定义 =====
    modules = struct(...
        'task',  {'分类',          '回归',          '聚类'},...
        'name',  {'KNN 分类器',    '回归分析',      'K-Means 聚类'},...
        'func',  {'demo_knn',      'demo_regression','demo_kmeans'},...
        'desc',  {'拖拽数据点改变分布，观察KNN决策边界实时变化；切换距离度量与加权投票策略',...
                  '拖拽数据点上下移动，观察多项式拟合曲线与过拟合/欠拟合的实时变化',...
                  '拖拽质心或数据点，观察聚类分配变化；单步/自动运行探索收敛过程'},...
        'color', {[0.2,0.6,0.85],  [0.5,0.5,0.85],  [0.85,0.55,0.2]},...
        'badge', {'基础',          '基础',          '进阶'});

    badgeColors = {[0.15,0.45,0.7],[0.15,0.45,0.7],[0.7,0.45,0.15]};

    % ===== 布局参数 =====
    % 第1行: 2个并排; 第2行: 1个居中
    nRows = 2;
    cardH = 0.22;
    cardW = 0.42;
    yRow1 = 0.54;
    yRow2 = yRow1 - cardH - 0.06;
    xLeft  = 0.05;
    xRight = 0.53;
    xCenter = 0.29;

    positions = [
        xLeft,  yRow1, cardW, cardH;   % KNN (左上)
        xRight, yRow1, cardW, cardH;   % 回归 (右上)
        xCenter,yRow2, cardW, cardH    % K-Means (中下)
    ];

    for i = 1:length(modules)
        pos = positions(i,:);
        xBase = pos(1); yBase = pos(2); cw = pos(3); ch = pos(4);
        c = modules(i).color;
        bc = badgeColors{i};

        % 卡片背景(深色带色调)
        uicontrol('Style','text','String','','Units','normalized',...
            'Position',[xBase,yBase,cw,ch],...
            'BackgroundColor',[c(1)*0.22,c(2)*0.22,c(3)*0.22]);

        % 左侧色条
        uicontrol('Style','text','String','','Units','normalized',...
            'Position',[xBase,yBase,0.006,ch],...
            'BackgroundColor',c);

        % 难度标签
        uicontrol('Style','text','String',modules(i).badge,...
            'FontSize',10,'FontWeight','bold',...
            'ForegroundColor',[1,1,1],...
            'BackgroundColor',[bc(1)*0.75,bc(2)*0.75,bc(3)*0.75],...
            'Units','normalized',...
            'Position',[xBase+0.02,yBase+ch-0.055,0.05,0.028]);

        % 任务类型标签
        uicontrol('Style','text','String',['[ ' modules(i).task ' ]'],...
            'FontSize',11,'ForegroundColor',[0,0,0],...
            'Units','normalized',...
            'Position',[xBase+0.075,yBase+ch-0.052,0.1,0.024]);

        % 模块名称
        uicontrol('Style','text','String',modules(i).name,...
            'FontSize',19,'FontWeight','bold',...
            'ForegroundColor',[0,0,0],'Units','normalized',...
            'Position',[xBase+0.02,yBase+ch-0.095,cw-0.04,0.038]);

        % 分隔线
        uicontrol('Style','text','String','','Units','normalized',...
            'Position',[xBase+0.02,yBase+ch-0.105,cw-0.04,0.002],...
            'BackgroundColor',[c(1)*0.5,c(2)*0.5,c(3)*0.5]);

        % 描述
        uicontrol('Style','text','String',modules(i).desc,...
            'FontSize',12,'ForegroundColor',[0,0,0],...
            'Units','normalized',...
            'Position',[xBase+0.02,yBase+0.03,cw-0.18,ch-0.14],...
            'HorizontalAlignment','left');

        % 进入按钮
        uicontrol('Style','pushbutton','String','进入学习  >>',...
            'FontSize',13,'FontWeight','bold',...
            'ForegroundColor',[1,1,1],...
            'BackgroundColor',c,'Units','normalized',...
            'Position',[xBase+cw-0.15,yBase+0.03,0.13,0.05],...
            'Callback',@(~,~) feval(modules(i).func));
    end

    % ===== 底部信息 =====
    uicontrol('Style','text',...
        'String','所有算法均从底层实现，无需额外工具箱 | 支持鼠标拖拽数据点进行交互探索',...
        'FontSize',11,'ForegroundColor',[0,0,0],...
        'Units','normalized','Position',[0.03,0.025,0.94,0.03],...
        'HorizontalAlignment','center');
end
